import { useQuery } from "@tanstack/react-query";
import type { NextPage } from "next";
import Head from "next/head";
import Cards from "../components/Cards";
import { env } from "../env/client.mjs";
import { Card, CardSchema } from "../types/Card";

const play = async () => {
	const res = await fetch(`${env.NEXT_PUBLIC_SERVER_URL}/play`);
	const data: unknown = await res.json();
	return await CardSchema.array().min(1).parse(data);
};

const Home: NextPage = () => {
	const { data: cards } = useQuery(["play"], play);

	return (
		<>
			<Head>
				<title>Drunk Knight</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>{cards && <Cards cards={cards} />}</main>
		</>
	);
};

export default Home;
