import type { NextPage } from "next";
import Head from "next/head";
import Cards from "../components/Cards";
import { Card } from "../types/Card";

const cards: Card[] = [
	{
		id: "1",
		name: "Alphabet",
		description: "Say the ABCs backwards, drink a second for each letter you didn't get",
		cardType: "ACTION",
	},
	{
		id: "2",
		name: "Dog Breads",
		description: "Go clockwise naming dog breads, first to fail drinks",
		cardType: "CATEGORIES",
	},
	{
		id: "3",
		name: "Favourite Colour",
		description: "If you share a favourite colour with another player, drink",
		cardType: "MAJORITY",
	},
];

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Drunk Knight</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>{cards && <Cards cards={cards} />}</main>
		</>
	);
};

export default Home;
